### ISSUE TITLE
About antlr4 run with wasm

### ISSUE THREAD

**Issue by wewoor** [mike-lischke/antlr4wasm#1]
Hey, @mike-lischke antlr4wasm is a good idea, we also thought about it before, but no fact action. Do you benchmark the performance in the browser with it?

**Comment by mike-lischke** [comment]
Currently it doesn't work yet, but once it does I will certainly compare the performance to what exists today (like antlr4ts).

**Comment by mike-lischke** [comment]
@wewoor Finally I got everything to run and collected some [performance numbers](https://github.com/mike-lischke/antlr4wasm/tree/master/benchmarks/mysql), including a discussion of the results. The WebAssembly target needs some improvements, however.
